package squid

var verbs = []string{"ambled", "assembled", "burst", "babbled", "charged", "chewed",
	"clamored", "coasted", "crawled", "crept", "danced", "dashed",
	"drove", "flopped", "galloped", "gathered", "glided", "hobbled",
	"hopped", "hurried", "hustled", "jogged", "juggled", "jumped",
	"laughed", "marched", "meandered", "munched", "passed", "plodded",
	"pranced", "ran", "raced", "rushed", "sailed", "sang", "sauntered",
	"scampered", "scurried", "skipped", "slogged", "slurped", "spied",
	"sprinted", "spurted", "squiggled", "squirmed", "stretched",
	"strode", "strut", "swam", "swung", "traveled", "trudged",
	"tumbled", "twisted", "wade", "wandered", "whistled", "wiggled",
	"wobbled", "yawned", "zipped", "zoomed"}

var adverbs = []string{"absentmindedly", "adventurously", "angrily", "anxiously",
	"awkwardly", "bashfully", "beautifully", "bleakly", "blissfully",
	"boastfully", "boldly", "bravely", "briskly", "calmly",
	"carefully", "cautiously", "cheerfully", "cleverly", "cluelessly",
	"clumsily", "coaxingly", "colorfully", "coolly", "courageously",
	"curiously", "daintily", "defiantly", "deliberately",
	"delightfully", "diligently", "dreamily", "drudgingly", "eagerly",
	"effortlessly", "elegantly", "energetically", "enthusiastically",
	"excitedly", "fervently", "foolishly", "furiously", "gallantly",
	"gently", "gladly", "gleefully", "gracefully", "gratefully",
	"happily", "hastily", "haphazardly", "hungrily", "innocently",
	"inquisitively", "intensely", "jokingly", "joshingly", "joyously",
	"jovially", "jubilantly", "kiddingly", "knavishly", "knottily",
	"kookily", "lazily", "loftily", "longingly", "lovingly", "loudly",
	"loyally", "madly", "majestically", "merrily", "mockingly",
	"mysteriously", "nervously", "noisily", "obnoxiously", "oddly",
	"optimistically", "overconfidently", "outside", "owlishly",
	"patiently", "playfully", "politely", "powerfully", "purposefully",
	"quaintly", "quarrelsomely", "queasily", "quickly", "quietly",
	"quirkily", "quizzically", "rapidly", "reassuringly", "recklessly",
	"reluctantly", "reproachfully", "sadly", "scarily", "seriously",
	"shakily", "sheepishly", "shyly", "silently", "sillily",
	"sleepily", "slowly", "speedily", "stealthily", "sternly",
	"suspiciously", "sweetly", "tenderly", "tensely", "thoughtfully",
	"triumphantly", "unabashedly", "unaccountably", "urgently",
	"vainly", "valiantly", "victoriously", "warmly", "wearily",
	"youthfully", "zestfully"}
